import { Organizacao } from "./types";

export const MOCK_ORGANIZACOES: Organizacao[] = [
  {
    id: "org1",
    nome: "Ydea Energia",
    tipo: "PJ",
    razaoSocial: "Ydea Energia Solar LTDA",
    nomeFantasia: "Ydea Energia",
    cnpj: "22.111.444/0001-33",
    telefone: "(84) 3222-4455",
    whatsapp: "(84) 99911-2233",
    email: "contato@ydeaenergia.com.br",
    site: "https://ydeaenergia.com.br",
    endereco: "Av. Engenheiro Roberto Freire",
    numero: "3000",
    bairro: "Capim Macio",
    cidade: "Natal",
    estado: "RN",
    cep: "59082-095",
    responsavel: "Marcos",
    canalOrigem: "Site",
    tags: ["parceiro"],
  },
  {
    id: "org2",
    nome: "Solar Engenharia",
    tipo: "PJ",
    razaoSocial: "Solar Engenharia e Projetos LTDA",
    cnpj: "18.775.220/0001-02",
    telefone: "(84) 3033-1100",
    whatsapp: "(84) 99122-3344",
    email: "comercial@solarengenharia.com.br",
    cidade: "Mossoró",
    estado: "RN",
    bairro: "Centro",
    responsavel: "Marcos",
    canalOrigem: "Indicação",
    tags: [],
  },
  {
    id: "org3",
    nome: "Empresa XPTO",
    tipo: "PJ",
    razaoSocial: "XPTO Comércio e Serviços LTDA",
    cnpj: "09.443.887/0001-55",
    telefone: "(84) 3211-9090",
    email: "financeiro@empresaxpto.com.br",
    cidade: "Natal",
    estado: "RN",
    responsavel: "Fernanda",
    canalOrigem: "Indicação",
    tags: [],
  },
  {
    id: "org4",
    nome: "Distribuidora Bom Preço LTDA",
    tipo: "PJ",
    razaoSocial: "Bom Preço Comércio de Alimentos LTDA",
    cnpj: "12.345.678/0001-90",
    telefone: "(84) 3222-1010",
    whatsapp: "(84) 99811-2233",
    email: "financeiro@bompreco.com.br",
    cidade: "Mossoró",
    estado: "RN",
    bairro: "Centro",
    responsavel: "YD",
    canalOrigem: "Site",
    tags: [],
  },
];
