import { Cliente } from "./types";

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "cli1",
    codigo: "CLI-0001",
    createdAt: "2026-02-14",
    tipoPessoa: "PF",
    nome: "João Paulo Medeiros",
    cpf: "045.221.330-11",
    telefone: "(84) 99123-4455",
    whatsapp: "(84) 99123-4455",
    email: "joaopaulo.medeiros@gmail.com",
    cidade: "Natal",
    estado: "RN",
    bairro: "Tirol",
    responsavel: "Marcos",
    temperatura: "quente",
    status: "cliente_ativo",
    score: 82,
    tags: ["financiamento"],
    distribuidora: "Cosern",
    unidadeConsumidora: "7027294116",
    consumoMedio: 480,
  },
  {
    id: "cli2",
    codigo: "CLI-0002",
    createdAt: "2026-04-02",
    tipoPessoa: "PJ",
    nome: "Distribuidora Bom Preço LTDA",
    razaoSocial: "Bom Preço Comércio de Alimentos LTDA",
    cnpj: "12.345.678/0001-90",
    telefone: "(84) 3222-1010",
    whatsapp: "(84) 99811-2233",
    email: "financeiro@bompreco.com.br",
    cidade: "Mossoró",
    estado: "RN",
    bairro: "Centro",
    responsavel: "YD",
    temperatura: "morno",
    status: "em_negociacao",
    score: 65,
    tags: [],
    distribuidora: "Cosern",
    consumoMedio: 3100,
  },
];
