import { Lead } from "./types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    cliente: "João Paulo Medeiros",
    local: "Casa — Bairro Tirol",
    tipo: "residencial",
    stage: "vistoria",
    potenciaKwp: 6.4,
    valor: 32000,
    responsavel: "Marcos",
    tags: ["financiamento"],
  },
  {
    id: "l2",
    cliente: "Kaue Victor",
    local: "Rua Geraldo da Costa Cirne",
    tipo: "residencial",
    stage: "concluido",
    potenciaKwp: 8.2,
    valor: 41000,
    responsavel: "Marcos",
    tags: [],
  },
  {
    id: "l3",
    cliente: "João Paulo Medeiros",
    local: "Galpão comercial — Zona Norte",
    tipo: "comercial",
    stage: "documentacao",
    potenciaKwp: 42,
    valor: 187000,
    responsavel: "Renata",
    tags: ["urgente"],
  },
  {
    id: "l4",
    cliente: "Ana Beatriz Souza",
    local: "Casa — Ponta Negra",
    tipo: "residencial",
    stage: "novo_lead",
    valor: 28500,
    responsavel: "Renata",
    tags: ["indicação"],
  },
  {
    id: "l5",
    cliente: "Fazenda Boa Vista",
    local: "Sítio — Zona Rural",
    tipo: "rural",
    stage: "novo_lead",
    valor: 96000,
    responsavel: "Marcos",
    tags: [],
  },
  {
    id: "l6",
    cliente: "Cláudio Ramalho",
    local: "Casa — Capim Macio",
    tipo: "residencial",
    stage: "projeto",
    potenciaKwp: 5.6,
    valor: 26000,
    responsavel: "Renata",
    tags: ["financiamento"],
  },
  {
    id: "l7",
    cliente: "Mercado Central",
    local: "Loja — Centro",
    tipo: "comercial",
    stage: "homologacao",
    potenciaKwp: 18,
    valor: 79000,
    responsavel: "Marcos",
    tags: [],
  },
  {
    id: "l8",
    cliente: "Patrícia Nogueira",
    local: "Casa — Lagoa Nova",
    tipo: "residencial",
    stage: "instalacao",
    potenciaKwp: 7.1,
    valor: 33500,
    responsavel: "Renata",
    tags: [],
  },
  {
    id: "l9",
    cliente: "Auto Posto Estrela",
    local: "Posto — BR-101",
    tipo: "comercial",
    stage: "comissionamento",
    potenciaKwp: 65,
    valor: 265000,
    responsavel: "Marcos",
    tags: ["urgente"],
  },
];
