import * as W from "./widgets";

export const WIDGET_REGISTRY: Record<string, React.ComponentType> = {
  "kpi.pipeline": W.KpiPipeline,
  "kpi.receita_mes": W.KpiReceitaMes,
  "kpi.meta_mes": W.KpiMetaMes,
  "kpi.conversao": W.KpiConversao,
  "kpi.ticket_medio": W.KpiTicketMedio,
  "kpi.projetos_instalados": W.KpiProjetosInstalados,
  "kpi.homologacoes": W.KpiHomologacoes,
  "kpi.propostas": W.KpiPropostas,
  "kpi.minhas_vendas": W.KpiMinhasVendas,
  "kpi.meus_leads": W.KpiMeusLeads,
  "kpi.minha_comissao": W.KpiMinhaComissao,
  "kpi.projetos_pendentes": W.KpiProjetosPendentes,
  "kpi.projetos_andamento": W.KpiProjetosAndamento,
  "kpi.vistorias_agendadas": W.KpiVistoriasAgendadas,
  "kpi.receita_total": W.KpiReceitaTotal,
  "kpi.financiamento_pendente": W.KpiFinanciamentoPendente,
  "kpi.instalacoes_hoje": W.KpiInstalacoesHoje,
  "kpi.comissionamento": W.KpiComissionamento,
  "kpi.concluidas": W.KpiConcluidas,
  "kpi.acompanhamentos_ativos": W.KpiAcompanhamentosAtivos,
  "kpi.nps_pendentes": W.KpiNpsPendentes,
  "kpi.ampliacoes": W.KpiAmpliacoes,
  "kpi.gestao_energetica": W.KpiGestaoEnergetica,
  "chart.pipeline_etapa": W.ChartPipelineEtapa,
  "chart.pipeline_engenharia": W.ChartPipelineEngenharia,
  "chart.vendas_mes": W.ChartVendasMes,
  "chart.funis": W.ChartFunis,
  "chart.pos_venda_funis": W.ChartPosVendaFunis,
  "chart.origem": W.ChartOrigem,
  "chart.distribuidoras": W.ChartDistribuidoras,
  "chart.potencia": W.ChartPotencia,
  "chart.leads_por_etapa": W.ChartLeadsPorEtapa,
};
